communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure

- terraform/development/main.tf
- terraform/modules/application/ecs.tf
- terraform/modules/application/roles.tf
- terraform/modules/application/variables.tf
- terraform/modules/bulk_upload/bucket.tf
- terraform/modules/bulk_upload/main.tf
- terraform/modules/bulk_upload/outputs.tf
- terraform/modules/bulk_upload/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
This PR is almost identical to https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure/pull/10. The differences are:
- different names (`bulk_upload` rather than `export`)
- slightly updated checkov/tfsec comments
> CLDC-2596: Add bulk upload bucket

- terraform/development/main.tf
- terraform/modules/application/security_groups.tf
- terraform/modules/application/variables.tf
- terraform/modules/front_door/outputs.tf
- terraform/modules/front_door/security_groups.tf
- terraform/modules/front_door/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
As mentioned in a comment on the [ticket](https://dluhcdigital.atlassian.net/browse/CLDC-2710), there was a mistake in the load balancer egress rule (`load_balancer_container_egress`). This has been fixed as part of this PR.
> CLDC-2710: Restrict ECS/LB security group ingress/egress rules

- terraform/modules/front_door/cloudfront.tf
- terraform/modules/front_door/policies.tf
- terraform/staging/main.tf
Basic cloudfront distribution with minimal encryption settings implemented (this will be done in later tickets).
Note that there doesn't seem to be good Terraform documentation for all the config options. Instead I used the CloudFront API documentation to understand what all the options were: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Types.html.
> CLDC-2545: set up CloudFront

- terraform/meta/.terraform.lock.hcl
- terraform/meta/main.tf
Forgot to update the role name to use the new `core-staging` prefix.
> CLDC-2711: fix prefix of task execution role name in meta

- terraform/development/main.tf
- terraform/meta/main.tf
- terraform/modules/backend/main.tf
- terraform/modules/front_door/cloudfront.tf
- terraform/modules/front_door/main.tf
- terraform/modules/front_door/variables.tf
- terraform/modules/front_door/waf.tf
- terraform/production/main.tf
- terraform/staging/main.tf
Setup WAF to cover our cloudfront distribution with the following AWS managed rules suggested on the ticket:
- `AWSManagedRulesCommonRuleSet` (excluding the `SizeRestrictions_BODY` rule to allow file uploads)
- `AWSManagedRulesKnownBadInputsRuleSet`
- `AWSManagedRulesAmazonIpReputationList`
I also added the following rule sets as they applied to our use case (as prompted by the ticket):
- `AWSManagedRulesSQLiRuleSet`
- `AWSManagedRulesLinuxRuleSet`
- `AWSManagedRulesUnixRuleSet`
See my comment on the rule priority order for more info about the rules and what they cover
> CLDC-2546: Set up WAF

- terraform/development/main.tf
- terraform/modules/front_door/cloudfront.tf
- terraform/modules/front_door/load_balancer.tf
- terraform/modules/front_door/policies.tf
- terraform/modules/front_door/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
The remainder of the original certificates work: updating the front door module to use the certificates generated, as well as enforcing HTTPs etc.
See https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure/pull/27/files for all of the certificates work in one place (I have manually replicated this over 2 PRs - this one and also https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure/pull/42/files).
In this PR I have also undone the change to the cloudfront origin request policy that was made in https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure/pull/25/files (this was necessary only whilst waiting for the certificates work to be done).
> Update front door with certificates work

- terraform/modules/cds_export/role_cds.tf
- terraform/modules/cds_export/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
- Update implementation to take multiple arns rather than one
- Hardcode the role ARNs given by CDS to enable access to our staging / prod export buckets
> CLDC-2764: add CDS role arns

- terraform/development/main.tf
- terraform/modules/front_door/cloudfront.tf
- terraform/modules/front_door/load_balancer.tf
- terraform/modules/front_door/security_groups.tf
- terraform/modules/front_door/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
Final edits necessary to get all the front door stuff working + more secure:
- Use http, not https, between load balancer and application
- Remove obsolete checkov and tfsec ignores
- Restrict the load balancer ingress to only accept https traffic from cloudfront
Will `fmt` once everything else has been finalised.
> Fix & improve load balancer + cloudfront

- terraform/modules/rds/alarms.tf
I found that the RDS alarms I created were in a state of 'insufficient data'. It's because I'd used `aws_db_instance.this.id` rather than `aws_db_instance.this.identifier` in Terraform (the the latter is the name of the db instance, which is what we want). I've updated this and now the alarms in cloudwatch look good 👍
> Fix RDS alarms

- terraform/development/main.tf
- terraform/modules/elasticache/outputs.tf
- terraform/modules/elasticache/parameter_groups.tf
- terraform/modules/elasticache/redis.tf
- terraform/modules/elasticache/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
https://dluhcdigital.atlassian.net/browse/CLDC-2756
Creating a highly-available (HA) setup with one primary and one replica node is most easily achieved by getting rid of the `aws_elasticache_cluster` resource entirely and using a `aws_elasticache_replication_group` resource instead. However we only want HA for some environments (prod and maybe staging), so I used a flag (at the redis module entrypoint) which is used in `count` expressions in the module to determine which of the resources gets created.
For now I've left staging with a HA setup in case whoever's reviewing this wants to test the failover. I can revert this to non-HA if needed though (the apply may take up to 30 minutes though - seems to take a long time to destroy and recreate these redis resources).
In terms of testing …
> CLDC-2756: Make redis highly available

- terraform/development/main.tf
- terraform/modules/application/alarms.tf
- terraform/modules/application/events.tf
- terraform/modules/front_door/alarms.tf
- terraform/modules/front_door/load_balancer.tf
- terraform/modules/front_door/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
As discussed, I've implemented:
- An alarm which looks for the "Essential container in task exited" event a certain number of times over a certain period
- An alarm which looks for any ECS Service Action issues (WARN or ERROR events)
- An alarm which checks for unhealthy hosts, and an alarm which checks whether the right number of healthy hosts
> CLDC-2785: App running tasks alarm

- terraform/development/main.tf
- terraform/modules/rds/database.tf
- terraform/modules/rds/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
- Implement a single DB read replica (i.e. Multi-AZ DB instance rather than cluster). I agree this is probably what Gov PaaS uses, and one replica is probably sufficient for CORE's requirements
- Implement a flag dictating if the replica will be made in the infra
- Set the flag to true for Prod only (staging is only true for now in case we need to test anything else during review, but will be removed once we're satisfied)
- I tested a DB failover using the instructions [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RebootInstance.html), essentially rebooting our primary DB with a failover. I could see the read replica take over, and a new replica take its place. The app seemed to handle failover fine. I was logged into CORE viewing lettings logs, triggered a failover …
> CLDC-2755: Make DB highly available

- terraform/development/main.tf
- terraform/modules/elasticache/redis.tf
- terraform/modules/elasticache/variables.tf
- terraform/modules/rds/database.tf
- terraform/modules/rds/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
Whether or not to apply changes immediately to rds and redis has been pulled out into a variable for each of those modules (as we want to apply changes immediately for some environments but not others).
> CLDC-2687: Update apply_immediately for rds & redis

- terraform/modules/application/logging.tf
- terraform/modules/rds_migration/ecs.tf
- terraform/modules/rds_migration/logging.tf
As part of [CLDC-2779](https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure/pull/60/files) I made some changes to logging which I wanted to make sure were replicated here (and I thought this was a nicer solution than waiting for the [migration PR](https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure/pull/49/files) to be merged to main).
The migration work doesn't have a 'role task' in the rds_migration module (unlike the application module). If that gets introduced, we should ensure it has the same (reduced) permissions as in the application module.
> CLDC-2779: Update logging in migration work

- terraform/development/.terraform.lock.hcl
I thought that not having dev infrastructure yet meant I didn't need to update this... unfortunately the `tf validate` check was still failing!
> Upgrade dev dependency lock file

- terraform/modules/application/ecs.tf
`REDIS_INSTANCE_NAME ` is no longer necessary - but has accidentally stuck around.
> Remove obsolete REDIS_INSTANCE_NAME

- terraform/modules/application/alarms.tf
- terraform/modules/application/ecs.tf
- terraform/modules/application/events.tf
I couldn't create healthy/unhealthy hosts alarms for sidekiq because there's no target group. I think it's fine not to have these given we're not expecting sidekiq tasks to fail anywhere near as much as the app tasks (correct me if I'm wrong!)
> CLDC-2786: Sidekiq alarms

- terraform/staging/main.tf
We've applied all the refactoring from CLDC-2811 to staging (see previous PRs), so these moved blocks could be removed now
> CLDC-2811: Remove no longer required moved blocks from staging

- terraform/modules/bulk_upload/bucket.tf
- terraform/modules/cds_export/bucket.tf
- Restrict the ability to make http connections with the our `bulk upload` and `cds export` buckets
I've checked the state and state replica buckets in the meta account, they both already have this enabled (through the external modules)
> CLDC-2909: Restrict http access to bulk upload and cds export buckets

- terraform/modules/github_actions_access/app_repo_role.tf
This was required for checking whether an image with a given tag already exists (as part of the aws deploy pipeline).
> Allow github actions to list ecr images

- terraform/modules/bulk_upload/access_log_bucket.tf
- terraform/modules/bulk_upload/bucket.tf
- terraform/modules/bulk_upload/outputs.tf
- terraform/modules/cds_export/access_log_bucket.tf
- terraform/modules/cds_export/bucket.tf
- terraform/modules/cds_export/outputs.tf
- terraform/modules/cds_export/role_cds.tf
- terraform/modules/cds_export/role_task_policy.tf
- terraform/production/main.tf
- terraform/staging/main.tf
- Enable access logging on the bulk upload and cds export buckets, with the logs going to the separate dedicated log buckets
- Check the access logs appear in the dedicated buckets ✅
> CLDC-2908: Implement access logging for bulk upload and cds export buckets

- terraform/modules/front_door/access_log_bucket.tf
- terraform/modules/front_door/load_balancer.tf
- terraform/modules/front_door/load_balancer_access_log_bucket.tf
- terraform/staging/.terraform.lock.hcl
- Enable access logging on the load balancer, with the logs going to a separate dedicated log bucket
- Check the access logs appear in the dedicated bucket ✅
> CLDC-2915: Implement load balancer access logging

- terraform/staging/main.tf
- Raised for visibility
- Upgrade the staging infra to temporarily match production, enabling us to test db migration and performance
- These changes / commits can be reverted once testing has been completed
> CLDC-NONE: upgrade staging infra temporarily to match production

- docs/environment_creation_from_scratch.md
- terraform/development/per_review_app/main.tf
- terraform/development/shared/main.tf
- terraform/development/shared/outputs.tf
- terraform/modules/application/ecs.tf
- terraform/modules/application/variables.tf
- terraform/modules/application_secrets/outputs.tf
- terraform/modules/application_secrets/secrets.tf
- terraform/production/.terraform.lock.hcl
- terraform/production/main.tf
- terraform/staging/main.tf
- Remove no longer required terraform moved blocks from Production
- Add a depends_on terraform statement to make apply commands smoother (in staging and prod)
- Update the docs about creating a new env from scratch
- Update the prod lock file for convenience
> CLDC-2608: Deploy Production Updates

- terraform/development/shared/main.tf
- terraform/modules/elasticache/redis.tf
- terraform/modules/rds/database.tf
- terraform/modules/rds/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
- Removed unrequired final snapshot config on the DB replica, as this doesn't / can't create any snapshots and it makes it harder to delete (necessary for the restore procedure)
- Added a final snapshot identifier for Redis. The Redis cluster has to be deleted as part of the restoration procedure, and I thought it would be good to have a final snapshot of it before so
- There are new docs for the backup and restoration procedures here to be reviewed. They aren't polished but the steps outline everything that needs to be done
[DB](https://dluhcdigital.atlassian.net/wiki/spaces/MC/pages/52166897/AWS+DB+Backup+and+Restore+Process)
[Redis](https://dluhcdigital.atlassian.net/wiki/spaces/MC/pages/52232460/AWS+Redis+Backup+and+Restore+Process)
> CLDC-2559: Test backup and restore procedures

- terraform/production/main.tf
- Bump up the app task CPU and Memory. We noticed the sales-log page was taking ~2/3s to load in AWS, compared to PaaS which took about ~1s). Bumping up these specs made the load times in AWS align with PaaS.
- Pre-filled the source S3 buckets for S3-migration from PaaS prod (we'll check this on migration day to ensure they are correct / the same)
> CLDC-2610: Update app task cpu and memory, and source s3 buckets for Prod

- docs/environment_creation_from_scratch.md
- terraform/development/shared/main.tf
- terraform/development/shared/variables.tf
- terraform/meta/main.tf
- terraform/meta/variables.tf
- terraform/modules/monitoring/kms.tf
- terraform/modules/monitoring/secrets.tf
- terraform/modules/monitoring/subscriptions.tf
- terraform/modules/monitoring/variables.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/staging/main.tf
- terraform/staging/variables.tf
I've tested this and it works. The team DL email address is saved in secrets manager, and I've just updated the team DL to include Rachael, Chirag and myself (this can easily be updated via HYP of course).
I've added some docs [here](https://dluhcdigital.atlassian.net/l/cp/wcf0bRKp) about the fact that when applying a new subscription in an environment, you'll get an error if you haven't already created the secret using `terraform apply -target="module.monitoring" -var="create_secrets_first=true"` and also set its value. There is a more comprehensive guide on this in `docs/environment_creation_from_scratch.md`.
> CLDC-2921: SNS email subscriptions

- terraform/modules/application/alarms.tf
This adds alarms for each ecs cluster that look at the max CPU / memory utilisation instead of the average. This would catch issues like the sidekiq one we saw the other day, where one task is running at full throttle for a long period of time but the other is normal, and thus the average is still quite low. 
I think both types are still valuable - the new ones will only alarm if max values are consistently high for 30 minutes, while the old will let us know that the average is high on a much shorter time basis. The old ones imply a potential overall capacity problem, the new ones something potentially wrong with one task in the system.
> Add alarms for max CPU and memory to catch single task problems

- terraform/development/per_review_app/main.tf
- terraform/modules/application/alarms.tf
- terraform/modules/application/variables.tf
We keep getting emails for these alarms going from insufficient data -> ok shortly after a review app is first set up.
For review apps, this is annoying and there is little risk by potentially ignoring lack of data.
For staging and prod, missing data should not happen because the environments are already set up (data shouldn't be missing during a release, just when the infra setup happens) so is concerning, hence we'll have these metrics alarm for missing data.
> Suppress missing data in alarms for review apps

- terraform/development/per_review_app/main.tf
- terraform/modules/application/alarms.tf
- terraform/modules/application/variables.tf
* Makes TriggeredRules alarms always treat missing data as not breaching - we weren't seeing these send a -> OK notification on creation because they never got any data (and only would if something was wrong)
* Suppresses -> OK notifications for review apps, because they happen on infra creation and are not important enough for that env to offset the noise
> Improve alarm setup

- terraform/development/shared/main.tf
- terraform/modules/rds/database.tf
- terraform/modules/rds/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
This looks like it will meet our actual usage needs very comfortably - it does assume we are not using too many review apps heavily at once, which feels like a safe assumption.
We may even be able to get away with micro instead of small, but the savings there are much smaller scale so it feels best to start with this.
> Cldc 3115 reduce dev db spec

- terraform/development/shared/main.tf
AWS won't allow you to reduce storage amounts in place, and it doesn't seem worth the effort of recreating the db right now.
> CLDC-3115: Restore dev db allocated storage amount as AWS won't allow reduction

- terraform/development/shared/main.tf
- terraform/modules/front_door/cloudfront.tf
- terraform/modules/front_door/load_balancer.tf
- terraform/modules/front_door/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
This (combined with the DNS changes) allows the site to be reached via either the old or new url
> CLDC-3616: Attach new certificates to cloudfront and load balancer

- terraform/modules/rds/alarms.tf
- Keep existing CPU alerts as a proxy for slow queries (slow query metrics are not exported to CloudWatch). Updated alert descriptions to include links to RDS Performance Insights for more actionable insights. Considered creating a lambda for custom metrics but it feels like more effort than necessary.
- Add an anomaly detection alarm for RDS CPU. This should be more adaptive and may catch performance issues earlier than static thresholds.
Hoping with the alert descriptions these might feel a bit more actionable. Default email format for alerts still feels like JSON vomit tho.
> Update alert descriptions and add rds_cpu_anomaly alert

- terraform/development/per_review_app/main.tf
- terraform/modules/application/ecs.tf
- terraform/modules/application/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
this lets us use the maximum amount of our memory requirement, and increase cpu in the future if needed
I'll suggest in documentation by default to use less than this, but setting the max to this allows us to create a task up to this size if required
> CLDC-4030: Add separate limits for ad hoc CPU & memory
